#!/bin/bash
echo "You have chosen custom installation. Choose which services to install"
	while true; do
		read -p "$* Install Wordpress? [y/n]: " yn
		case $yn in 
			[Yy]*) bash Scripts/wpInstall;;
			[Nn]*) echo "You chose no" ;;
		esac

		read -p "$* Install MySQL? [y/n]: " yn2
		case $yn2 in 
			[Yy]*) bash Scripts/mysqlInstall;;
			[Nn]*) echo "You chose no" ;;
		esac

	done


