#!/bin/bash
echo "You have chosen custom installation. Choose which services to install"
	while true; do
		read -p "$* Install Wordpress? [y/n]: " yn
		case $yn in 
			[Yy]*) bash Scripts/wpInstall;;
			[Nn]*) echo "You chose no" ;;
		esac

		read -p "$* Install MySQL? [y/n]: " yn2
		case $yn2 in 
			[Yy]*) bash Scripts/mysqlInstall;;
			[Nn]*) echo "You chose no" ;;
		esac

		read -p "$* Install GitLab? [y/n]: " yn3
		case $yn3 in
			[Yy]*) echo "Sorry, GitLab integration is still in development" #bash Scripts/gitLabInstall
		esac

		break
	done


