#!/bin/bash

read -p "This will install and configure Wordpress, MySQL, and GitLab. Proceed?" answer
case ${answer:0:1} in
    y|Y ) 
	bash Scripts/wpInstall
	bash Scripts/mySQLInstall
	echo "Unfortuantely GitLab is not available at this time" #bash Scripts/gitLabInstall
	break 
	;;
    n|N )
        break
    ;;

    * ) echo "Sorry, that's not a valid input"
esac

