#!/bin/bash

read -p "This will install and configure Wordpress, MySQL, and GitLab. Proceed?" answer
case ${answer:0:1} in
    y|Y ) 
	bash Scripts/wpInstall
	#UNCOMMENT WHEN READY bash Scripts/mySQLInstall
	;;
    * )
        echo No
    ;;
esac

