#!/bin/bash
pw="$(dd if=/dev/urandom bs=1 count=12 2>/dev/null | base64 -w 0 | rev | cut -b 2- | rev )" #use urandom function to make a password
echo "
	Your MySQL Password is $pw

"
#COME BACK TO THIS STUFF

cat <<EOF >./kustomization.yaml
secretGenerator:
- name: mysql-pass
  literals:
  - password=$pw
EOF
