#!/bin/bash
#pw=tr -cd '[:alnum:]' < /dev/urandom | fold -w10 | head -n 1 #use urandom function to make a password
#echo "
#	Your MySQL Secret Password is $pw
#
#"
#COME BACK TO THIS STUFF

cat <<EOF >./kustomization.yaml
secretGenerator:
- name: mysql-pass
  literals:A@n6,#v~N-qFpnHm
  - password=Y
EOF
