#!/bin/bash

(cd Files; wget https://k8s.io/examples/application/wordpress/wordpress-deployment.yaml) 
(cd Files; wget https://k8s.io/examples/application/wordpress/mysql-deployment.yaml)
(cd Scripts; ./makeSecret)
(cd Scripts; ./addDepFiles)
(cd Scripts; mv kustomization.yaml ../Files)
(cd Files; kubectl apply -k ./)
kubectl get pvc #&& echo MySQL PV Successfully Created || echo MySQL PV Was Not Created  
kubectl get pods
minikube service wordpress --url
