#!/bin/bash

pw="$(dd if=/dev/urandom bs=1 count=12 2>/dev/null | base64 -w 0 | rev | cut -b 2- | rev )" #use urandom function to make a password
echo "
	Your MySQL Password is $pw

"

cat <<EOF >./../Files/sSQLSecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: kubernetes.io/basic-auth
stringData:
  password:$pw 
EOF

(cd Files; kubectl apply -f sSQLSecret.yaml)
